version: '3'
services:
  drupal:
    image: drupal:9
    container_name: "monconteneur_drupal"
    ports:
      - 8080:80
    volumes:
      - ./web:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=drupaldock
      - MYSQL_USER=user_drupal
      - MYSQL_PASSWORD=mdp_drupal
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=drupaldock
      - MYSQL_USER=user_drupal
      - MYSQL_PASSWORD=mdp_drupal
      - MYSQL_ROOT_PASSWORD=root
